export { default as addAmpBoilerplate } from './addAmpBoilerplate'
export { default as addAmpScript } from './addAmpScript'
export { default as addCharset } from './addCharset'
export { default as addViewport } from './addViewport'
export { default as convertToDom } from './convertToDom'
export { default as setAmpOnHtml } from './setAmpOnHtml'
export { default as strip } from './strip'
